### ISSUE TITLE
Icons component missing

### ISSUE THREAD

**Issue by khawarizmus** [DesignRevision/shards-vue#17]
## Expected Behavior
According to the documentation, the only place where an icon is used is in the navigation and it was used this way:

```html
<fa :icon="['fas', 'search']" />
```

however, when I do I get an error that the component `fa` is not registered

## Current Behavior
There is no documentation on how to use icons nor an icon component. 

Note: I have tried to use the `<i/>` tag but it didn't work either.

## Steps to Reproduce
described in first section

## Possible Solution
Implement the `fa` component ?

**Comment by nickvasdev** [comment]
@gimyboya Thanks for submitting this! Actually, in order to be able to use the Font Awesome icons you would have to manually integrate the [`vue-fontawesome`](https://github.com/FortAwesome/vue-fontawesome) library that also provides the proper component. Please make sure to check out their documentation to learn more about how you can use the library and register the icons you'd like to use. 😄
